from pathlib import Path
import hashlib
import json

def write_file_checked(path, content):
    path = Path(path)
    path.write_text(content, encoding='utf-8', newline='\n')
    payload = {
        'path': str(path),
        'size_bytes': path.stat().st_size,
        'sha256': hashlib.sha256(path.read_bytes()).hexdigest(),
    }
    print(json.dumps(payload, sort_keys=True))

write_file_checked('anti086_winmode_micro.yaml', 'stage: micro\nmicro_stack_test_only: true\nnot_095_candidate: true\nnot_main_training: true\nnot_submission_ready: true\nanti086_input_root: auto\nbase_model_path: /kaggle/input/models/metric/nemotron-3-nano-30b-a3b-bf16/transformers/default/1\nparent_adapter_path: auto_or_none\ncorpus_file: winmode_micro.jsonl\nmax_rows: 64\ntoken_output: /kaggle/working/anti086_tokens/micro/train_tokens.jsonl\ntoken_output_dir: /kaggle/working/anti086_tokens/micro\ntoken_manifest_path: /kaggle/working/anti086_tokens/micro/token_manifest.json\noutput_adapter_dir: /kaggle/working/anti086_adapters/micro\ntrain_manifest_path: /kaggle/working/anti086_adapters/micro/train_manifest.json\neval_output_dir: /kaggle/working/anti086_eval/micro\nmax_seq_len: 768\nbatch_size: 1\nmicro_batch_size: 1\ngradient_accumulation: 4\ntarget_modules: q_proj,k_proj,v_proj,o_proj,up_proj,down_proj,in_proj,out_proj,lm_head\nadapter_size_limit_mb: 1500\nrank: 32\nlearning_rate: 0.0000003\nnum_steps: 20\nfull_prompt_loss: false\nanswer_format: raw\neval_mode: smoke_16\nvllm_max_model_len: 8192\nvllm_max_tokens: 64\nvllm_max_num_seqs: 16\nvllm_gpu_memory_utilization: 0.85\n')
write_file_checked('anti086_winmode_v1.yaml', 'stage: v1\nanti086_input_root: auto\nbase_model_path: /kaggle/input/models/metric/nemotron-3-nano-30b-a3b-bf16/transformers/default/1\nparent_adapter_path: none\ncorpus_file: corpus_anti086_v1.jsonl\nmax_rows: 1000\ntoken_output: /kaggle/working/anti086_tokens/v1/train_tokens.jsonl\ntoken_output_dir: /kaggle/working/anti086_tokens/v1\ntoken_manifest_path: /kaggle/working/anti086_tokens/v1/token_manifest.json\noutput_adapter_dir: /kaggle/working/anti086_adapters/v1\ntrain_manifest_path: /kaggle/working/anti086_adapters/v1/train_manifest.json\neval_output_dir: /kaggle/working/anti086_eval/v1\nmax_seq_len: 1024\nbatch_size: 1\nmicro_batch_size: 1\ngradient_accumulation: 8\ntarget_modules: q_proj,v_proj\nadapter_size_limit_mb: 512\nrank: 8\nlearning_rate: 0.0000002\nnum_steps: 75\nfull_prompt_loss: false\nanswer_format: raw\neval_mode: smoke_16\nhf_fallback_eval: true\nmax_eval_rows: 16\nvllm_max_model_len: 8192\nvllm_max_tokens: 128\nvllm_max_num_seqs: 16\nvllm_gpu_memory_utilization: 0.85\n')
write_file_checked('anti086_winmode_v1b.yaml', 'stage: v1b\nexperiment_label: direct_answer_parent_continuation_v1b\nnot_submission_ready: true\nno_package: true\nno_submit: true\nanti086_input_root: auto\nbase_model_path: /kaggle/input/models/metric/nemotron-3-nano-30b-a3b-bf16/transformers/default/1\nparent_adapter_path: none\ncorpus_file: corpus_anti086_v1.jsonl\ndirect_answer_only: true\nmax_rows: 1500\ntoken_output: /kaggle/working/anti086_tokens/v1b/train_tokens.jsonl\ntoken_output_dir: /kaggle/working/anti086_tokens/v1b\ntoken_manifest_path: /kaggle/working/anti086_tokens/v1b/token_manifest.json\noutput_adapter_dir: /kaggle/working/anti086_adapters/v1b\ntrain_manifest_path: /kaggle/working/anti086_adapters/v1b/train_manifest.json\neval_output_dir: /kaggle/working/anti086_eval/v1b\ncalibrated_eval_path: /kaggle/working/anti086_eval/v1b/parent_calibrated_eval.jsonl\nparent_calibration_report_path: /kaggle/working/anti086_eval/v1b/parent_calibration_report.json\nmax_seq_len: 1024\nbatch_size: 1\nmicro_batch_size: 1\ngradient_accumulation: 8\ntarget_modules: q_proj,v_proj\nadapter_size_limit_mb: 512\nrank: 8\nlearning_rate: 0.00000008\nnum_steps: 75\nfull_prompt_loss: false\nanswer_format: raw\neval_mode: parent_calibrated_64\nhf_fallback_eval: true\nmax_eval_rows: 64\nvllm_max_model_len: 8192\nvllm_max_tokens: 128\nvllm_max_num_seqs: 16\nvllm_gpu_memory_utilization: 0.85\n')
