"""Pass 11 external training backend boundary APIs."""

from .adapter_validator import (
    AdapterValidationConfig,
    AdapterValidationError,
    AdapterValidationReport,
    compute_adapter_artifact_hashes,
    validate_adapter_config_file,
    validate_adapter_output,
)
from .backend_bridge import (
    BackendBridgeError,
    build_invocation_from_dpo_plan,
    build_invocation_from_final_sft_refresh,
    build_invocation_from_grpo_plan,
    build_invocation_from_sft_plan,
    build_run_manifest_from_backend_outputs,
)
from .backend_contracts import (
    BackendArtifactRef,
    BackendContractError,
    BackendInvocation,
    BackendKind,
    BackendMetric,
    BackendResult,
    BackendStatus,
    TrainingStage,
    compute_backend_result_hash,
    validate_backend_invocation,
    validate_backend_result,
)
from .backend_runner import (
    BackendRunReport,
    BackendRunnerConfig,
    BackendRunnerError,
    invoke_training_backend,
    validate_backend_callable_result,
)
from .run_manifest import (
    TrainingRunManifest,
    TrainingRunManifestError,
    build_training_run_manifest,
    compute_training_run_manifest_hash,
    validate_training_run_manifest,
)
from .training_log_validator import (
    ALLOWED_METRICS,
    TrainingLogValidationConfig,
    TrainingLogValidationError,
    TrainingLogValidationReport,
    parse_training_log_lines,
    validate_metric_series,
    validate_training_log,
)

__all__ = [
    "ALLOWED_METRICS",
    "AdapterValidationConfig",
    "AdapterValidationError",
    "AdapterValidationReport",
    "BackendArtifactRef",
    "BackendBridgeError",
    "BackendContractError",
    "BackendInvocation",
    "BackendKind",
    "BackendMetric",
    "BackendResult",
    "BackendRunReport",
    "BackendRunnerConfig",
    "BackendRunnerError",
    "BackendStatus",
    "TrainingLogValidationConfig",
    "TrainingLogValidationError",
    "TrainingLogValidationReport",
    "TrainingRunManifest",
    "TrainingRunManifestError",
    "TrainingStage",
    "build_invocation_from_dpo_plan",
    "build_invocation_from_final_sft_refresh",
    "build_invocation_from_grpo_plan",
    "build_invocation_from_sft_plan",
    "build_run_manifest_from_backend_outputs",
    "build_training_run_manifest",
    "compute_adapter_artifact_hashes",
    "compute_backend_result_hash",
    "compute_training_run_manifest_hash",
    "invoke_training_backend",
    "parse_training_log_lines",
    "validate_adapter_config_file",
    "validate_adapter_output",
    "validate_backend_callable_result",
    "validate_backend_invocation",
    "validate_backend_result",
    "validate_metric_series",
    "validate_training_log",
    "validate_training_run_manifest",
]
