"""Scoring boundary helpers for ``nemotron_engine``."""

from .answer_extractor import (
    ANSWER_MAX,
    ANSWER_MIN,
    AnswerExtractionError,
    BoxedSpan,
    ExtractedAnswer,
    extract_answer,
    extract_boxed_answer,
    extract_final_answer,
    find_boxed_spans,
    has_truncation_risk,
    has_valid_answer,
    normalize_answer_candidate,
)
from .format_policy import (
    AnswerFormatError,
    AnswerType,
    CanonicalAnswer,
    FormatCheck,
    FormatPolicy,
    is_valid_response_format,
    normalize_answer,
    render_final_answer,
    validate_answer,
    validate_response_format,
)
from .local_scorer import ScoreResult, accuracy, score_answer, score_batch, score_completion

__all__ = [
    "ANSWER_MAX",
    "ANSWER_MIN",
    "AnswerExtractionError",
    "AnswerFormatError",
    "AnswerType",
    "BoxedSpan",
    "CanonicalAnswer",
    "ExtractedAnswer",
    "FormatCheck",
    "FormatPolicy",
    "ScoreResult",
    "accuracy",
    "extract_answer",
    "extract_boxed_answer",
    "extract_final_answer",
    "find_boxed_spans",
    "has_truncation_risk",
    "has_valid_answer",
    "is_valid_response_format",
    "normalize_answer",
    "normalize_answer_candidate",
    "render_final_answer",
    "score_completion",
    "score_answer",
    "score_batch",
    "validate_answer",
    "validate_response_format",
]
